builder = "youtong._.0826#9250"
token = "OTIxNjczODg2MDQ5OTEwNzk1.Yb2Vsg.FVLrGLXJy_CPMM_9P2YlOFO-HXI"
update = "無"

g1 = "趴在草地上，總是能聽見大地的心跳聲"
g2 = "萬商雲來，千船繼至，百貨疊出，人們用這樣的話語來評價璃月"
g3 = "你好 我叫甘雨 是來自璃月的仙人(實際上是半人半仙)"
g4 = "甘雨總是一個人孤獨地走在璃月繁華的街道上 又或是獨自一人坐在絕雲間的懸崖邊"
g5 = "縱然世人得知我的地位，恐怕他们也很難將月海亭的秘書與破曉時分站在碼頭上與安静享用早点的少女聯繫起来"
g6 = "甘雨作為月海亭的秘書，承擔了諸多世人看不見的工作"
g7 = "璃月每個決議背後的數據支撐，每條新頒布條例的摘錄和整編，都是由甘雨一絲不苟地完成的"
g8 = "每日破曉時分，甘雨會站在碼頭上享用早點但在旭日東升之前，她一定會重新回到高踞玉京台之上的月海亭，繼續完成她與岩王帝君簽訂的契約"
g9 = "甘雨的愛好是工作，只要工作，她就會感到開心"
g10 = "她的工作，就是遵循與帝君的'契約'，為璃月的多數生命，謀求最大的福祉"
g11 = "飲必甘露，食必嘉禾 這是甘雨的守則"
g12 = "清心很苦，但甘雨卻認為清心的花瓣特別好吃。"
g13 = "習慣了城市生活的甘雨，會非常在意自己的體型與體重。 不自覺地便會被美味吸引，又要嚴格控制好自己的進食"
g14 = "儘管麒麟一族是嚴格的素食主義者，但璃月料理作為天下美食之集大成作，即使是素菜，也會令食客難以控制食慾。"
g15 = "甘雨不敢在玉京台栽種清心，生怕哪天一個不小心就會忍不住吃掉它"
g16 = "甘雨的特色料理名為'盛世太平'，甘雨懷揣著對世間的美好祈願烹製菜肴，再將自己最喜歡的清心花瓣點綴其上。"
g17 = "生活在璃月的每一隻小狗，甘雨都給它們取了名字"
g18 = "麒麟憩於花叢的畫面，光是觀賞就能讓心情平靜下來"
g19 = "甘雨喜歡在庭院聽雨的感覺，但這對工作量很大的她來說太奢侈了"
g20 = "甘雨有著仙獸「麒麟」血脈這件事情，在璃月港鮮為人知"
g21 = "一旦脫離了工作的範疇，甘雨就很容易顯露出本性上的與眾不同之處。"
g22 = "甘雨有睡午覺的習慣，同時彷彿內置了極其精準的生物鍾。 一旦到了午休時間，便不分地點不分場合，只要將身子蜷作一團就能立刻睡著"
g23 = "或許是身為仙獸的混血後裔，甘雨對世間事物的認知，與多數的人類原本就有所不同"
g24 = "麒麟是仙獸中的仁獸，飲必甘露，食必嘉禾。 不履生蟲，不折生草，不群居，不旅行，不入阱陷，幽閒則循循如也，動則有容儀，是溫柔而優雅的一族。"
g25 = "而當海中巨獸為非作惡、足下的土地遭遇危機時，和平便不再成為生活的選項。 三千年前，甘雨回應岩之神摩拉克斯的召喚，成為他在魔神戰爭中的助力。 \
    戰爭結束后，她選擇留在璃月幫助人們建設更完美的城邦。"
g26 = "初代璃月七星需要輔佐，甘雨毅然接過這一差事，出任他們的秘書。 她作出這一決定的瞬間，'神之眼'在腰間閃現，令她擁有了超越肉身、與世界共鳴的力量。 \
    這一刻，甘雨內心充滿了平和的安定感。"
g27 = "哪怕變得更為強大，也無需驅動'神之眼'之力，而是將'神之眼'作為保護璃月的終極手段。 作為仙獸與人類的混血，她選擇成為兩個種族的橋樑。\
     '神之眼'，便是她的新責任與新見證"
g28 = ""
g29 = ""
g30 = ""

ganyu = [g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14,g15,g16,g17,g18,g19,g20,g21,g22,g23,g24,g25,g26,g27]


p1 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\1.jpg"
p2 = "C:\\Users\\Aspire 5\\OneDrive\\文件\GitHub\\Ganyu_Bot\\pic\\2.jpg"
p3 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\3.jpg"
p4 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\4.jpg"
p5 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\5.jpg"
p6 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\6.jpg"
p7 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\7.jpg"
p8 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\8.jpg"
p9 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\9.jpg"
p10 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\10.jpg"
p11 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\11.jpg"
p12 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\12.jpg"
p13 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\13.jpg"
p14 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\14.jpg"
p15 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\15.jpg"
p16 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\16.jpg"
p17 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\17.jpg"
p18 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\18.jpg"
p19 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\19.jpg"
p20 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\20.jpg"
p21 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\21.jpg"
p22 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\22.jpg"
p23 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\23.jpg"
p24 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\24.jpg"
p25 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\25.jpg"
p26 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\26.jpg"
p27 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\27.jpg"
p28 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\28.jpg"
p29 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\29.jpg"
p30 = "C:\\Users\\Aspire 5\\OneDrive\\文件\\GitHub\\Ganyu_Bot\\pic\\30.jpg"
pic = [p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30]